# Generated by Django 4.1.3 on 2022-12-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tododata',
            old_name='titel',
            new_name='title',
        ),
    ]
