# Generated by Django 4.1.3 on 2022-12-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbview',
            name='Sates',
        ),
    ]
