# Generated by Django 4.1.3 on 2023-02-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('course', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
