# Generated by Django 4.1.3 on 2022-12-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdata',
            name='Comment',
            field=models.CharField(default='hi', max_length=1000),
        ),
    ]
