# Generated by Django 4.1.3 on 2022-12-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='fee',
            field=models.IntegerField(),
        ),
    ]
