# Generated by Django 4.1.3 on 2023-01-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_feedbackdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
